# syntax=docker/dockerfile:1

FROM golang:1.21 as build
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY server.go ./
RUN CGO_ENABLED=0 GOOS=linux go build server.go

FROM alpine:3.18 as release
WORKDIR /
COPY --from=build /app/server /server
EXPOSE 8080
ENTRYPOINT ["/server"]
