version: '3.8'

services:
  echo-roach:
    depends_on:
      - roachdb
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: echo-server
    hostname: echo-server
    networks:
      - roachnet
    ports:
      - 80:8080
    environment:
      - PGUSER=${PGUSER:-totoro}
      - PGPASSWORD=${PGPASSWORD:?database password not set}
      - PGHOST=${PGHOST:-db}
      - PGPORT=${PGPORT:-26257}
      - PGDATABASE=${PGDATABASE:-mydb}
    deploy:
      restart_policy:
        condition: on-failure
  roachdb:
    image: cockroachdb/cockroach:latest-v23.1
    container_name: roachdb
    hostname: db
    networks:
      - roachnet
    ports:
      - 26257:26257
      - 8080:8080
    volumes:
      - roach:/cockroach/cockroach-data
    command: start-single-node --insecure

volumes:
  roach:

networks:
  roachnet:
    driver: bridge


